/*
 * build.c -- bld.h build script for curl
 *
 * Builds libcurl (static library) and the curl CLI executable.
 * Replicates the essential parts of curl's CMake build:
 *   - lib/ sources  -> libcurl.a  (with subdirs: vtls, vauth, vquic, vssh)
 *   - src/ sources  -> curl       (with curlx helper files from lib)
 *
 * Feature detection generates curl_checks.h and curl_config.h at build time.
 *
 * Usage:
 *   cc -std=c11 -w build.c -o b -lpthread
 *   ./b build
 *   ./b build -Dssl=off -Dzlib=off
 *   ./b build --release
 *   ./build/bin/curl --version
 */

#define BLD_IMPLEMENTATION
#define BLD_STRIP_PREFIX
#include "../../bld.h"

BLD_RECOMPILE_CMD("cc -std=c11 -w build.c -lpthread")

static const char* os_name(Bld_OsTarget os) {
    switch (os) {
    case BLD_OS_LINUX:   return "Linux";
    case BLD_OS_MACOS:   return "Darwin";
    case BLD_OS_FREEBSD: return "FreeBSD";
    case BLD_OS_WINDOWS: return "Windows";
    }
    return "Unknown";
}

static void write_curl_config_h(Bld* b, bool has_ipv6,
                                const char* ca_bundle, const char* ca_path) {
    bld_fs_mkdir_p(bld_filepath("generated"));
    FILE* f = fopen("generated/curl_config.h", "w");
    if (!f) {
        bld_log_info("[!] failed to create generated/curl_config.h\n");
        return;
    }
    const char* os = os_name(b->toolchain->os);
    fprintf(f,
        "/* Generated by build.c — do not edit */\n"
        "#ifndef CURL_CONFIG_H\n"
        "#define CURL_CONFIG_H\n"
        "\n"
        "/* Feature detection results */\n"
        "#include \"curl_checks.h\"\n"
        "\n"
        "/* Platform (detected from toolchain) */\n"
        "#define OS \"%s\"\n"
        "#define CURL_OS \"%s\"\n"
        "#define STDC_HEADERS 1\n"
        "#ifdef HAVE_FILE_OFFSET_BITS\n"
        "#define _FILE_OFFSET_BITS 64\n"
        "#endif\n"
        "\n"
        "/* gethostbyname_r — detected variant defines HAVE_GETHOSTBYNAME_R */\n"
        "#if defined(HAVE_GETHOSTBYNAME_R_6) || defined(HAVE_GETHOSTBYNAME_R_5) || defined(HAVE_GETHOSTBYNAME_R_3)\n"
        "#define HAVE_GETHOSTBYNAME_R 1\n"
        "#endif\n"
        "\n"
        "/* fsetxattr — detected variant defines HAVE_FSETXATTR */\n"
        "#if defined(HAVE_FSETXATTR_5) || defined(HAVE_FSETXATTR_6)\n"
        "#define HAVE_FSETXATTR 1\n"
        "#endif\n"
        "\n"
        "/* Threading — detected from compile checks */\n"
        "#ifdef USE_THREADS_POSIX\n"
        "#define USE_RESOLV_THREADED 1\n"
        "#endif\n"
        "#if defined(HAVE_WINDOWS_H) && !defined(USE_THREADS_POSIX)\n"
        "#define USE_THREADS_WIN32 1\n"
        "#endif\n",
        os, os);

    /* strerror_r: curl requires exactly one variant.
     * -w suppresses type warnings so both checks may pass. prefer glibc with _GNU_SOURCE.
     * if neither detected, default to POSIX. */
    fprintf(f,
        "\n#if defined(HAVE_POSIX_STRERROR_R) && defined(HAVE_GLIBC_STRERROR_R)\n"
        "#undef HAVE_POSIX_STRERROR_R\n"
        "#endif\n"
        "#if !defined(HAVE_POSIX_STRERROR_R) && !defined(HAVE_GLIBC_STRERROR_R)\n"
        "#define HAVE_POSIX_STRERROR_R 1\n"
        "#endif\n");

    /* CA bundle — from user option or detected */
    if (ca_bundle && ca_bundle[0])
        fprintf(f, "\n#define CURL_CA_BUNDLE \"%s\"\n", ca_bundle);
    if (ca_path && ca_path[0])
        fprintf(f, "#define CURL_CA_PATH \"%s\"\n", ca_path);

    /* IPv6 — detected via compile check */
    if (has_ipv6)
        fprintf(f, "\n#define ENABLE_IPV6 1\n");

    fprintf(f, "\n#endif /* CURL_CONFIG_H */\n");
    fclose(f);
}

void configure(Bld* b) {
    set_compiler_c(b, .standard = BLD_C_GNU11);
    b->global_defines = BLD_STRS("_GNU_SOURCE");

    /* ------------------------------------------------------------------ */
    /* User options                                                        */
    /* ------------------------------------------------------------------ */
    bool use_ssl  = option_bool(b, "ssl",  "Enable OpenSSL support", true);
    bool use_zlib = option_bool(b, "zlib", "Enable zlib compression", true);
    bool use_ipv6 = option_bool(b, "ipv6", "Enable IPv6 support", true);
    const char* ca_bundle = option_str(b, "ca-bundle", "CA bundle path",
        "/etc/ssl/certs/ca-certificates.crt");
    const char* ca_path = option_str(b, "ca-path", "CA path",
        "/etc/ssl/certs");

    /* ------------------------------------------------------------------ */
    /* External dependencies (pkg-config)                                  */
    /* ------------------------------------------------------------------ */
    Bld_Target* dep_ssl  = use_ssl  ? find_pkg(b, "openssl") : NULL;
    Bld_Target* dep_zlib = use_zlib ? find_pkg(b, "zlib")    : NULL;

    /* ------------------------------------------------------------------ */
    /* Feature detection                                                   */
    /* ------------------------------------------------------------------ */
    Bld_Checks* chk = checks_new(b);

    /* --- Headers --- */
    checks_header(chk, "HAVE_ARPA_INET_H",     "arpa/inet.h");
    checks_header(chk, "HAVE_DIRENT_H",         "dirent.h");
    checks_header(chk, "HAVE_FCNTL_H",          "fcntl.h");
    checks_header(chk, "HAVE_IFADDRS_H",        "ifaddrs.h");
    checks_header(chk, "HAVE_LIBGEN_H",         "libgen.h");
    checks_header(chk, "HAVE_LINUX_TCP_H",      "linux/tcp.h");
    checks_header(chk, "HAVE_LOCALE_H",         "locale.h");
    checks_header(chk, "HAVE_NETDB_H",          "netdb.h");
    checks_header(chk, "HAVE_NETINET_IN_H",     "netinet/in.h");
    checks_header(chk, "HAVE_NETINET_TCP_H",    "netinet/tcp.h");
    checks_header(chk, "HAVE_NETINET_UDP_H",    "netinet/udp.h");
    checks_header(chk, "HAVE_NET_IF_H",         "net/if.h");
    checks_header(chk, "HAVE_POLL_H",           "poll.h");
    checks_header(chk, "HAVE_PWD_H",            "pwd.h");
    checks_header(chk, "HAVE_STDATOMIC_H",      "stdatomic.h");
    checks_header(chk, "HAVE_STDBOOL_H",        "stdbool.h");
    checks_header(chk, "HAVE_STRINGS_H",        "strings.h");
    checks_header(chk, "HAVE_SYS_EVENTFD_H",    "sys/eventfd.h");
    checks_header(chk, "HAVE_SYS_FILIO_H",      "sys/filio.h");
    checks_header(chk, "HAVE_SYS_IOCTL_H",      "sys/ioctl.h");
    checks_header(chk, "HAVE_SYS_PARAM_H",      "sys/param.h");
    checks_header(chk, "HAVE_SYS_POLL_H",       "sys/poll.h");
    checks_header(chk, "HAVE_SYS_RESOURCE_H",   "sys/resource.h");
    checks_header(chk, "HAVE_SYS_SELECT_H",     "sys/select.h");
    checks_header(chk, "HAVE_SYS_SOCKET_H",     "sys/socket.h");
    checks_header(chk, "HAVE_SYS_SOCKIO_H",     "sys/sockio.h");
    checks_header(chk, "HAVE_SYS_TYPES_H",      "sys/types.h");
    checks_header(chk, "HAVE_SYS_UN_H",         "sys/un.h");
    checks_header(chk, "HAVE_SYS_UTIME_H",      "sys/utime.h");
    checks_header(chk, "HAVE_TERMIO_H",         "termio.h");
    checks_header(chk, "HAVE_TERMIOS_H",        "termios.h");
    checks_header(chk, "HAVE_SYS_STAT_H",       "sys/stat.h");
    checks_header(chk, "HAVE_SYS_TIME_H",       "sys/time.h");
    checks_header(chk, "HAVE_UNISTD_H",         "unistd.h");
    checks_header(chk, "HAVE_UTIME_H",          "utime.h");
    checks_header(chk, "HAVE_PTHREAD_H",        "pthread.h");
    checks_header(chk, "HAVE_NETINET_IN6_H",    "netinet/in6.h");
    checks_header(chk, "HAVE_STROPTS_H",        "stropts.h");
    checks_header(chk, "HAVE_WINDOWS_H",        "windows.h");
    checks_header(chk, "HAVE_WINSOCK2_H",       "winsock2.h");

    /* --- Functions --- */
    checks_func(chk, "HAVE_ALARM",            "alarm",            "unistd.h");
    checks_func(chk, "HAVE_BASENAME",         "basename",         "libgen.h");
    checks_func(chk, "HAVE_FCNTL",            "fcntl",            "fcntl.h");
    checks_func(chk, "HAVE_FNMATCH",          "fnmatch",          "fnmatch.h");
    checks_func(chk, "HAVE_FREEADDRINFO",     "freeaddrinfo",     "netdb.h");
    checks_func(chk, "HAVE_FSEEKO",           "fseeko",           "stdio.h");
    checks_func(chk, "HAVE_GETADDRINFO",      "getaddrinfo",      "netdb.h");
    checks_func(chk, "HAVE_GETEUID",          "geteuid",          "unistd.h");
    checks_func(chk, "HAVE_GETHOSTNAME",      "gethostname",      "unistd.h");
    checks_func(chk, "HAVE_GETIFADDRS",       "getifaddrs",       "ifaddrs.h");
    checks_func(chk, "HAVE_GETPEERNAME",      "getpeername",      "sys/socket.h");
    checks_func(chk, "HAVE_GETPWUID",         "getpwuid",         "pwd.h");
    checks_func(chk, "HAVE_GETPWUID_R",       "getpwuid_r",       "pwd.h");
    checks_func(chk, "HAVE_GETRLIMIT",        "getrlimit",        "sys/resource.h");
    checks_func(chk, "HAVE_GETSOCKNAME",      "getsockname",      "sys/socket.h");
    checks_func(chk, "HAVE_GETTIMEOFDAY",     "gettimeofday",     "sys/time.h");
    checks_func(chk, "HAVE_GMTIME_R",         "gmtime_r",         "time.h");
    checks_func(chk, "HAVE_IF_NAMETOINDEX",   "if_nametoindex",   "net/if.h");
    checks_func(chk, "HAVE_INET_NTOP",        "inet_ntop",        "arpa/inet.h");
    checks_func(chk, "HAVE_INET_PTON",        "inet_pton",        "arpa/inet.h");
    checks_func(chk, "HAVE_LOCALTIME_R",      "localtime_r",      "time.h");
    checks_func(chk, "HAVE_OPENDIR",          "opendir",          "dirent.h");
    checks_func(chk, "HAVE_PIPE",             "pipe",             "unistd.h");
    checks_func(chk, "HAVE_POLL",             "poll",             "poll.h");
    checks_func(chk, "HAVE_REALPATH",         "realpath",         "stdlib.h");
    checks_func(chk, "HAVE_RECV",             "recv",             "sys/socket.h");
    checks_func(chk, "HAVE_SCHED_YIELD",      "sched_yield",      "sched.h");
    checks_func(chk, "HAVE_SELECT",           "select",           "sys/select.h");
    checks_func(chk, "HAVE_SEND",             "send",             "sys/socket.h");
    checks_func(chk, "HAVE_SENDMSG",          "sendmsg",          "sys/socket.h");
    checks_func(chk, "HAVE_SETLOCALE",        "setlocale",        "locale.h");
    checks_func(chk, "HAVE_SETRLIMIT",        "setrlimit",        "sys/resource.h");
    checks_func(chk, "HAVE_SIGACTION",        "sigaction",        "signal.h");
    checks_func(chk, "HAVE_SIGNAL",           "signal",           "signal.h");
    checks_func(chk, "HAVE_SOCKET",           "socket",           "sys/socket.h");
    checks_func(chk, "HAVE_SOCKETPAIR",       "socketpair",       "sys/socket.h");
    checks_func(chk, "HAVE_STRCASECMP",       "strcasecmp",       "strings.h");
    checks_func(chk, "HAVE_STRERROR_R",       "strerror_r",       "string.h");
    checks_func(chk, "HAVE_UTIME",            "utime",            "utime.h");
    checks_func(chk, "HAVE_UTIMES",           "utimes",           "sys/time.h");
    checks_func(chk, "HAVE_ACCEPT4",          "accept4",          "sys/socket.h");
    checks_func(chk, "HAVE_PIPE2",            "pipe2",            "unistd.h");
    checks_func(chk, "HAVE_SENDMMSG",         "sendmmsg",         "sys/socket.h");
    checks_func(chk, "HAVE_MEMRCHR",          "memrchr",          "string.h");
    checks_func(chk, "HAVE_EVENTFD",          "eventfd",          "sys/eventfd.h");
    checks_func(chk, "HAVE_ARC4RANDOM",       "arc4random",       "stdlib.h");
    checks_func(chk, "HAVE_FTRUNCATE",        "ftruncate",        "unistd.h");
    checks_func(chk, "HAVE_GETPPID",          "getppid",          "unistd.h");
    checks_func(chk, "HAVE_SNPRINTF",         "snprintf",         "stdio.h");
    checks_func(chk, "HAVE_STRDUP",           "strdup",           "string.h");
    checks_func(chk, "HAVE_STRTOK_R",         "strtok_r",         "string.h");
    checks_func(chk, "HAVE_STRTOLL",          "strtoll",          "stdlib.h");

    /* --- Compile checks (complex feature detection) --- */
    checks_compile(chk, "HAVE_POSIX_STRERROR_R",
        "#include <string.h>\nint main(void) { char buf[100]; int r = strerror_r(0, buf, sizeof(buf)); (void)r; return 0; }");
    checks_compile(chk, "HAVE_GLIBC_STRERROR_R",
        "#include <string.h>\nint main(void) { char buf[100]; char *r = strerror_r(0, buf, sizeof(buf)); (void)r; return 0; }");
    checks_compile(chk, "HAVE_GETHOSTBYNAME_R_6",
        "#include <netdb.h>\nint main(void) { struct hostent h, *hp; char buf[1024]; int err;\n  gethostbyname_r(\"\", &h, buf, sizeof(buf), &hp, &err); return 0; }");
    checks_compile(chk, "HAVE_GETHOSTBYNAME_R_5",
        "#include <netdb.h>\nint main(void) { struct hostent h; char buf[1024]; int err;\n  gethostbyname_r(\"\", &h, buf, sizeof(buf), &err); return 0; }");
    checks_compile(chk, "HAVE_GETHOSTBYNAME_R_3",
        "#include <netdb.h>\nint main(void) { struct hostent_data data; struct hostent h;\n  gethostbyname_r(\"\", &h, &data); return 0; }");
    checks_compile(chk, "HAVE_FSETXATTR_5",
        "#include <sys/xattr.h>\nint main(void) { fsetxattr(0, \"\", \"\", 0, 0); return 0; }");
    checks_compile(chk, "HAVE_FSETXATTR_6",
        "#include <sys/xattr.h>\nint main(void) { fsetxattr(0, \"\", \"\", 0, 0, 0); return 0; }");
    checks_compile(chk, "HAVE_SOCKADDR_IN6_SIN6_SCOPE_ID",
        "#include <sys/types.h>\n#include <netinet/in.h>\nint main(void) { struct sockaddr_in6 s; s.sin6_scope_id = 0; return 0; }");
    checks_compile(chk, "USE_UNIX_SOCKETS",
        "#include <sys/socket.h>\n#include <sys/un.h>\nint main(void) { struct sockaddr_un a; a.sun_family = AF_UNIX; return 0; }");
    checks_compile(chk, "HAVE_CLOCK_GETTIME_MONOTONIC_RAW",
        "#include <time.h>\nint main(void) { struct timespec ts; clock_gettime(CLOCK_MONOTONIC_RAW, &ts); return 0; }");
    checks_compile(chk, "HAVE_GETADDRINFO_THREADSAFE",
        "#include <netdb.h>\nint main(void) {\n#if defined(__linux__) || defined(__GLIBC__)\n  return 0;\n#else\n#error not threadsafe\n#endif\n}");
    checks_compile(chk, "HAVE_DECL_FSEEKO",
        "#include <stdio.h>\nint main(void) { fseeko(stdin, 0, SEEK_SET); return 0; }");
    checks_compile(chk, "HAVE_SIGSETJMP",
        "#include <setjmp.h>\nint main(void) { sigjmp_buf buf; sigsetjmp(buf, 0); return 0; }");
    checks_compile(chk, "HAVE_SIGINTERRUPT",
        "#include <signal.h>\nint main(void) { siginterrupt(SIGTERM, 1); return 0; }");
    checks_compile(chk, "HAVE_MSG_NOSIGNAL",
        "#include <sys/socket.h>\nint main(void) { int x = MSG_NOSIGNAL; (void)x; return 0; }");
    checks_compile(chk, "HAVE_FCNTL_O_NONBLOCK",
        "#include <fcntl.h>\nint main(void) { int x = O_NONBLOCK; (void)x; return 0; }");
    checks_compile(chk, "HAVE_FILE_OFFSET_BITS",
        "#define _FILE_OFFSET_BITS 64\n#include <sys/types.h>\nint x[sizeof(off_t) >= 8 ? 1 : -1];\nint main(void) { return 0; }");
    checks_compile(chk, "USE_THREADS_POSIX",
        "#include <pthread.h>\nint main(void) { pthread_t t; (void)t; return 0; }");
    checks_compile(chk, "HAVE_LONGLONG",
        "int main(void) { long long x = 0; (void)x; return 0; }");
    checks_compile(chk, "HAVE_BOOL_T",
        "#include <stdbool.h>\nint main(void) { bool x = true; (void)x; return 0; }");
    checks_compile(chk, "HAVE_STRUCT_TIMEVAL",
        "#include <sys/time.h>\nint main(void) { struct timeval tv; tv.tv_sec = 0; tv.tv_usec = 0; return 0; }");
    checks_compile(chk, "HAVE_STRUCT_SOCKADDR_STORAGE",
        "#include <sys/socket.h>\nint main(void) { struct sockaddr_storage ss; (void)ss; return 0; }");
    checks_compile(chk, "HAVE_CLOCK_GETTIME_MONOTONIC",
        "#include <time.h>\nint main(void) { struct timespec ts; clock_gettime(CLOCK_MONOTONIC, &ts); return 0; }");
    checks_compile(chk, "HAVE_ATOMIC",
        "#include <stdatomic.h>\nint main(void) { _Atomic int x = 0; (void)x; return 0; }");
    checks_compile(chk, "HAVE_VARIADIC_MACROS_C99",
        "#define TEST(x, ...) x\nint main(void) { TEST(0, 1, 2); return 0; }");
    checks_compile(chk, "HAVE_WRITABLE_ARGV",
        "int main(int argc, char **argv) { argv[0][0] = ' '; return 0; }");
    checks_compile(chk, "HAVE_SUSECONDS_T",
        "#include <sys/time.h>\nint main(void) { suseconds_t x = 0; (void)x; return 0; }");
    checks_compile(chk, "HAVE_SA_FAMILY_T",
        "#include <sys/socket.h>\nint main(void) { sa_family_t x = 0; (void)x; return 0; }");
    bool* has_ipv6 = checks_compile(chk, "HAVE_IPV6",
        "#include <sys/types.h>\n#include <sys/socket.h>\n#include <netinet/in.h>\n"
        "int main(void) { struct sockaddr_in6 s; s.sin6_family = AF_INET6; return 0; }");

    /* --- Sizes --- */
    checks_sizeof(chk, "SIZEOF_INT",        "int");
    checks_sizeof(chk, "SIZEOF_LONG",       "long");
    checks_sizeof(chk, "SIZEOF_OFF_T",      "off_t");
    checks_sizeof(chk, "SIZEOF_SIZE_T",     "size_t");
    checks_sizeof(chk, "SIZEOF_TIME_T",     "time_t");
    checks_sizeof(chk, "SIZEOF_CURL_OFF_T", "long long");

    /* Run all checks in parallel, write results */
    checks_run(chk);
    bld_fs_mkdir_p(bld_filepath("generated"));
    checks_write(chk, "generated/curl_checks.h");

    /* Generate curl_config.h (wraps curl_checks.h with extra platform defines) */
    write_curl_config_h(b, use_ipv6 && *has_ipv6, ca_bundle, ca_path);

    /* ------------------------------------------------------------------ */
    /* Common compile flags                                                */
    /* ------------------------------------------------------------------ */
    Bld_Strs lib_defines = {0};
    if (b->toolchain->os != BLD_OS_WINDOWS)
        strs_push(&lib_defines, "HAVE_CONFIG_H");  /* Windows: use curl's config-win32.h */
    strs_push(&lib_defines, "BUILDING_LIBCURL");
    strs_push(&lib_defines, "CURL_STATICLIB");
    /* Disable features we do not have headers for */
    strs_push(&lib_defines, "CURL_DISABLE_LDAP");
    strs_push(&lib_defines, "CURL_DISABLE_LDAPS");

    if (dep_ssl && dep_ssl->found)
        strs_push(&lib_defines, "USE_OPENSSL");
    if (dep_zlib && dep_zlib->found)
        strs_push(&lib_defines, "HAVE_LIBZ");

    Bld_CompileFlags lib_cflags = default_compile_flags(b);
    lib_cflags.defines      = lib_defines;
    lib_cflags.include_dirs = BLD_PATHS("prj/include", "prj/lib", "generated");

    /* ------------------------------------------------------------------ */
    /* libcurl -- static library                                           */
    /* ------------------------------------------------------------------ */

    /* Gather all lib/ .c files recursively (includes vtls, vauth, vquic, vssh) */
    Bld_Paths lib_srcs = files_glob("prj/lib/**/*.c");

    /* Exclude files that require missing platform headers or are Windows-only */
    lib_srcs = files_exclude(lib_srcs, BLD_PATHS(
        "prj/lib/ldap.c",           /* needs LDAP headers */
        "prj/lib/openldap.c",       /* needs LDAP headers */
        "prj/lib/dllmain.c"         /* Windows DLL entry point */
    ));

    /* System libraries */
    Bld_Strs sys_libs = {0};
    if (b->toolchain->os == BLD_OS_WINDOWS) {
        strs_push(&sys_libs, "ws2_32");
        strs_push(&sys_libs, "bcrypt");
        strs_push(&sys_libs, "crypt32");
    } else {
        strs_push(&sys_libs, "pthread");
        if (b->toolchain->os == BLD_OS_LINUX) {
            strs_push(&sys_libs, "dl");
            strs_push(&sys_libs, "rt");
        }
    }

    Bld_Target* libcurl = add_lib(b,
        .name              = "curl",
        .desc              = "libcurl -- the multiprotocol file transfer library",
        .lib_basename      = "curl",
        .sources           = lib_srcs,
        .compile           = lib_cflags,
        .compile_pub = {
            .include_dirs = BLD_PATHS("prj/include"),
            .defines      = BLD_STRS("CURL_STATICLIB"),
        },
        .link_pub    = {
            .libs = sys_libs,
        });

    /* Link external deps (only if found — these are optional) */
    if (dep_ssl  && dep_ssl->found)  link_with(libcurl, dep_ssl);
    if (dep_zlib && dep_zlib->found) link_with(libcurl, dep_zlib);

    /* ------------------------------------------------------------------ */
    /* curl CLI executable                                                 */
    /* ------------------------------------------------------------------ */

    /* src/*.c -- the curl tool sources */
    Bld_Paths exe_srcs = files_glob("prj/src/*.c");

    /* Exclude Windows resource file */
    exe_srcs = files_exclude(exe_srcs, BLD_PATHS("prj/src/curl.rc"));

    /*
     * curlx helper files: these are lib/ sources reused by the curl CLI.
     * They are compiled into the exe WITHOUT BUILDING_LIBCURL, so they get
     * the tool's compile flags instead.
     * See src/Makefile.inc CURLX_CFILES for the canonical list.
     */
    Bld_Paths curlx_srcs = BLD_PATHS(
        "prj/lib/base64.c",
        "prj/lib/curl_get_line.c",
        "prj/lib/curl_multibyte.c",
        "prj/lib/dynbuf.c",
        "prj/lib/nonblock.c",
        "prj/lib/strtoofft.c",
        "prj/lib/timediff.c",
        "prj/lib/version_win32.c",
        "prj/lib/warnless.c"
    );

    Bld_Paths all_exe_srcs = files_merge(exe_srcs, curlx_srcs);

    Bld_Strs exe_defines = {0};
    if (b->toolchain->os != BLD_OS_WINDOWS)
        strs_push(&exe_defines, "HAVE_CONFIG_H");
    strs_push(&exe_defines, "CURL_STATICLIB");

    if (dep_ssl && dep_ssl->found)
        strs_push(&exe_defines, "USE_OPENSSL");
    if (dep_zlib && dep_zlib->found)
        strs_push(&exe_defines, "HAVE_LIBZ");

    Bld_CompileFlags exe_cflags = default_compile_flags(b);
    exe_cflags.defines      = exe_defines;
    exe_cflags.include_dirs = BLD_PATHS("prj/include", "prj/lib", "generated", "prj/src");

    Bld_Target* curl_exe = add_exe(b,
        .name    = "curl",
        .desc    = "curl -- command line tool for transferring data with URLs",
        .sources = all_exe_srcs,
        .compile = exe_cflags);

    /* Link against libcurl (propagates include dirs and system libs) */
    link_with(curl_exe, libcurl);

    /* ------------------------------------------------------------------ */
    /* Installation                                                        */
    /* ------------------------------------------------------------------ */
    install_exe(b, curl_exe);
    install_lib(b, libcurl);
    install_dir(b, "prj/include/curl", bld_filepath("include/curl"));
}
